# Generated by Django 4.2.4 on 2023-08-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_app_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['id']},
        ),
    ]
